spring:
  application:
    name: signup
   
welcome:
  message: Hello world - Spring Config Client Test at March 15 2019 12:34 PM
  date: 02/01/2019
    
voicemail:
  whitelist:
    tn: +12151111111,+12152222222
